### ISSUE TITLE
Randomly sampling frames to reduce images processed during metrics calculation

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#10]
Reposting idea by @Sorkanius from last Friday's call.

We can consider randomly sampling frames from videos to reduce images that need to be processed during metrics calculation

**Comment by Sorkanius** [comment]
We will also have to test how this affects inference accuracy

**Comment by ndujar** [comment]
A first good approach is to make a leap frog every n frames

**Comment by ndujar** [comment]
Tests resulted in noticeable computation time reduction with 1s chunks instead of 4s, with some effect over accuracy.
Regarding leapfrogging or random sampling, the current implementation (using OpenCV VideoCapture.read()) doesn't allow significant time reductions, as OpenCV reads every frame in between. To avoid this subsequent overhead we would need to refactor how video frames are being collected and ocnverted to numpy arrays.
