### ISSUE TITLE
Explore direct extraction of metrics/features from bitstream

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#37]
For transcoder self-verification (i.e. checking if it would pass verification prior to returning a result), if we can directly extract metrics/features from the bitstream we might be able to skip additional decoding steps for the transcoder since it is already decoding the source during transcoding. [PyAV](https://github.com/mikeboers/PyAV) might help in exploring whether this is possible by getting access to the demuxed stream.

**Comment by ndujar** [comment]
We have managed to read and represent information obtained from the bitstream of h264 encoded videos and:

- Read motion vectors for each frame of a segment.
- Extract the contents of P, I and B frames into numpy arrays.
- Extract Huffman tables in binary format.

Nevertheless, bitstream feature definition is subject to codec re-implementation from our side. The reconstruction of frames from the above information depends on our own interpretation of the h264 standard. This might easily turn into a maintenance burden given the large number of existing codecs we would need to support.

On the other hand, the option of generating features without making any reconstruction of frames would render features that are too abstract and give far worse results in terms of accuracy. These features contain too few information for a model to be trained with, as we have seen through our previous research. This is why we have slowly been discarding them in favor of those containing more information.
In the present situation, we have narrowed down our features set to:
- temporal gaussian mean square error
- temporal gaussian difference mean 
- discrete cosine transform's minimum and maximum difference.
These features require the computation of the gaussian blurred frame and also the dct for each pair of input / output frames, for which the complete representation of the frames is needed.

For these reasons, we advise against pursuing this path any further.

**Comment by yondonfu** [comment]
> Nevertheless, bitstream feature definition is subject to codec re-implementation from our side. The reconstruction of frames from the above information depends on our own interpretation of the h264 standard. 

For personal clarification - this is because there is no standard method for reconstructing the decoded frames for a h264 encoded video using just the contents & motion vectors for encoded frames along with Huffman tables and as a result for each new codec supported a custom frame reconstruction algorithm based on that information would need to be implemented? And to summarize, the concern is around the maintenance burden associated with the frame reconstruction algorithm implementation per codec?

> On the other hand, the option of generating features without making any reconstruction of frames would render features that are too abstract and give far worse results in terms of accuracy. These features contain too few information for a model to be trained with, as we have seen through our previous research.

Sounds like we can rule out direct feature extraction from an encoded bitstream *without* frame reconstruction due to its likely negative impact on classification accuracy (since the available features without frame reconstruction contain too little information for model training). But, putting aside the maintenance burden for a moment, it sounds like direct feature extraction from a bitstream *with* frame reconstruction is still feasible? The advice against pursuing this path is noted, but I'm curious about the feasibility of the approach if maintenance burden was not a concern.

**Comment by ndujar** [comment]
>For personal clarification - this is because there is no standard method for reconstructing the decoded frames for a h264 encoded video using just the contents & motion vectors for encoded frames along with Huffman tables and as a result for each new codec supported a custom frame reconstruction algorithm based on that information would need to be implemented? And to summarize, the concern is around the maintenance burden associated with the frame reconstruction algorithm implementation per codec?

There are standard methods for reconstructing the decoded frames for H264. Actually, the standard is fairly strict. However, because the standard is merely indicative, different decoder implementations may differ in their output quality for the same encoded input.

Image below depicts all the different coding tools each of the standard's profile can use:
![image.png](https://images.zenhubusercontent.com/5cf0489817221c71b75cc4e4/b0f1d69c-6926-4d19-a966-0de7aad08022) Source: H.265 (HEVC) bitstream to H.264 (MPEG 4 AVC) bitstream transcoder by Deepak Hingole

However the decoder chooses to implement those tools (Redundant slice, CABAC,...) is entirely up to them.
So basically, if we would restrict Livepeer broadcasters to use libavcodec's implementation of H264 (which is too restrictive), we would need to support, at least, its four profiles (Main, Baseline, High and Extended). Otherwise there is no certainty that whatever feature we extract is consistent. 
Moreover, there is still no guarantee that the Orchestrator is using the same decoder so its input for transcoding might still be flawed even before beginning the work.

**Comment by ndujar** [comment]
>Sounds like we can rule out direct feature extraction from an encoded bitstream without frame reconstruction due to its likely negative impact on classification accuracy (since the available features without frame reconstruction contain too little information for model training). But, putting aside the maintenance burden for a moment, it sounds like direct feature extraction from a bitstream with frame reconstruction is still feasible? The advice against pursuing this path is noted, but I'm curious about the feasibility of the approach if maintenance burden was not a concern.

One of the issues with respect to feature extraction from bitstream is that so far we have only managed to get good results with those involving the gaussian filter and DCT comparison.
Some [authors](https://www.researchgate.net/publication/277902635_Predicting_Full-Reference_Video_Quality_Measures_using_HEVC_Bitstream-Based_No-Reference_Features) have found promising correlations between different quality metrics (PSNR, PVQM, VIF and VQM) and selected bitstream features extracted H265/HEVC generated streams.
However, the correlations found are to quality metrics whose value we have already tested as features for our own model with no success.
Moreover, the mindset of this form of studies assumes a default "good intention" in the transcoding. This means that we might be opening a number of vulnerabilities given the lower amount of information that we are supplying to the classifier. In the example publication, only statistics about Coding Units (block size related), Prediction Units (P, B and I frame types), Motion Vectors (horizontal and vertical) and Quantization Parameter (coding severity) are extracted.

**Comment by yondonfu** [comment]
> However, because the standard is merely indicative, different decoder implementations may differ in their output quality for the same encoded input.

Got it. My understanding is that similarly, the decoded frame reconstruction implementation using just content and motion vectors from frames as well as Huffman tables may also differ in output quality for the same encoded input. 

> So basically, if we would restrict Livepeer broadcasters to use libavcodec's implementation of H264 (a fairly restrictive scenario), we would need to support, at least, its four profiles (Main, Baseline, High and Extended). Otherwise there is no certainty that whatever feature we extract is consistent.

Got it. So, in this case, the classifier would need to support all 4 profiles because the decoded frame reconstruction implementation needs to be able to handle input that could've been created with any of the 4 profiles.

> Moreover, there is still no guarantee that the Orchestrator is using the same decoder so its input for transcoding might still be flawed even before beginning the work.

What do you mean by "same decoder"? Same as the classifier?

**Comment by ndujar** [comment]
>What do you mean by "same decoder"? Same as the classifier?

I mean that different Orchestrators may have different choices of decoder implementations. For example, a Broadcaster can be using Apple's H.264 encoder (which conforms to Main profile), but the Orchestrator may have decided for transcoding with Cisco's OpenH264 (also compliant to Main profile).
However, in such case, it could happen that, given the different implementations of the standard, the decoder in the Orchestrator side misplaces the information received through the bitstream provided by the Broadcaster, supplying an input for the subsequent transcodification that is of different quality from the original.
In [this link](http://www.compression.ru/video/codec_comparison/pdf/msu_mpeg_4_avc_h264_codec_comparison_2007_eng.pdf) it is possible to observe how different implementations of the same standard produce different qualities.

![image.png](https://images.zenhubusercontent.com/5cf0489817221c71b75cc4e4/b6e6fe48-6cbf-40ec-9469-119588944ee1)

In a way, this complicates somehow the process of self-verification. In order to ensure complete objectivity in the process, the same decoder implementation has to be used at every Orchestrator's entry to create the testing samples if we want self-verification to be 100% accurate.

Alternatively, Broadcasters could generate their testing samples at time of encoding and send them to Orchestrators in parallel with the segment. Then Orchestrators would be able to verify themselves by extracting the features from the comparison between their generated samples and those received and decide whether deliver the job or not.
