### ISSUE TITLE
Verify md5 hash of audio stream

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#60]
## Background

Once livepeer/go-livepeer#1073 is merged, transcoders will copy the audio stream instead of transcoding audio into AAC which enables bitexact audio verification - we can verify that an audio stream was not tampered simply by computing the md5 hash of the audio stream of the source and comparing it with the md5 hash of the audio stream in a result.

## Feature

The verifier can extract the audio stream from a set of results, calculate their md5 hashes and compare those hashes with the expected md5 hash which can be provided with a request (calculated from the audio stream of the original source).

We can update the API request object to:

```
{
    ...
    "renditions: [
        {
            "uri": ...,
            "resolution": {},
            "frame_rate": ...,
            "audio_hash": ...
        }
    ]
}
```

The API response object would be updated to include a field indicating if the audio stream md5 hash check passed or failed.

**Comment by j0sh** [comment]
> the expected md5 hash which can be provided with a request

Since we are passing in the source anyway, could the hash be calculated from the source without passing it in, and the per-rendition comparison done from there?

There's a few things to note here:
* Naturally only the audio stream should be hashed; any video needs to be separated out first. ([Example of doing this using the Livepeer LPMS library](https://github.com/livepeer/lpms/pull/150); that PR also has unit tests incorporating ffmpeg CLI equivalent hash checks on audio)
* If no audio is present in the source, then no audio should be present in the results.
* The FFmpeg `md5` (or `hash`) muxer ignores timestamps, which is fine for our case, because otherwise the verifier would have to take timestamp rewriting into consideration. (The `framemd5`/`framehash` muxers do take timestamps into consideration, but this would break for us unless the verifier re-implements timestamp rescaling. We should still check timestamp validity at some point, but that's outside the scope of audio verification.)
* Implementing audio verification probably requires another pass through the source and each transcoded result, separate from the video processing. No decoding is required here, so it should be a relatively quick operation.

For future reference: the AAC bitstream format may legitimately change between containers such as mpegts (ADTS format) and MP4 (ASC format). Currently we only use mpegts, so this is not a problem. However, in the future, conversion to a canonical format may be required prior to hashing [1], along with a reliable way to determine the source and transcoded formats.

[1] This is just a bitstream re-serialization and doesn't modify the compressed data itself.

**Comment by yondonfu** [comment]
> Since we are passing in the source anyway, could the hash be calculated from the source without passing it in, and the per-rendition comparison done from there?

Yeah that makes sense. I think an added benefit is that we wouldn't need to worry about making sure the verifier's behavior matches ffmpeg's behavior w.r.t hashing the audio stream (maybe this isn't that much of a concern anyway, but this would definitely make it not a concern) since the audio hashes for both the sources and results will be calculated by the verifier (instead of having ffmpeg calculate the audio hash for the source).

> The FFmpeg md5 (or hash) muxer ignores timestamps, which is fine for our case, because otherwise the verifier would have to take timestamp rewriting into consideration.

If all the audio hashes are calculated by the verifier ffmpeg muxer behavior shouldn't matter right? Seems like ffmpeg's handling of timestamps would only matter if we had ffmpeg calculate the audio hash for the source forcing the verifier to calculate the audio hash the same way (ie. considering timestamp rewriting).

**Comment by j0sh** [comment]
> If all the audio hashes are calculated by the verifier ffmpeg muxer behavior shouldn't matter right?

It matters because if the verifier re-implements the hash checking, it needs to exclude timestamps and any other metadata that's not already part of the bitstream. Although I think it'd be easier to just use ffmpeg itself, unless there are facilities for extracting and processing the audio here.

**Comment by yondonfu** [comment]
> It matters because if the verifier re-implements the hash checking, it needs to exclude timestamps and any other metadata that's not already part of the bitstream, because those are not likely to match between the source and transcoded results

Ah right I see what you're saying now about excluding timestamps + metadata that wouldn't match between the source and the results - thanks for the clarification.

**Comment by ndujar** [comment]
> It matters because if the verifier re-implements the hash checking, it needs to exclude timestamps and any other metadata that's not already part of the bitstream, because those are not likely to match between the source and transcoded results. Although I think it'd be easier to just use ffmpeg itself, unless there are facilities for extracting and processing the audio here.

A solution has been implemented using ffmpeg to extract the audio directly from the .mp4 files of source and renditions, as it was indeed the easiest approach. It creates a .wav file as a PCM signed 16-bit little-endian (-acodec pcm_s16le), from which the signal can be read.
It contemplates the cases when audio is not available (as is the case with the current training data set) and adds an extra parameter ['audio_avaliable'] to the response.
However, instead of using the hash, this implementation compares signals using an euclidean distance. This values of distance is stored in the ['audio_dist'] parameter.
This has (IMO) some advantages:
* Removes the need of making the extra step of computing the hash.
* Gives a "soft" measure of how much distorted the signal is is provided, instead of a pass / fail (please note PSNR or any other metric can also be used instead of euclidean distance)
* Is more aligned with the metrics-based video verification
