### ISSUE TITLE
Performance benchmarking

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#7]
Two performance data points that would be helpful to inform discussions around how the verification tool will be used are:

- The computation time when running the verification tool
- The computation cost (in terms of computation resources i.e. CPU usage, memory usage, etc.) of running the verification tool

For background, there are a few instances where computation time/cost and false negative rate will either affect the feasibility/practicality of a mechanism or the parameters of the mechanism:

- We are currently planning on having a broadcaster randomly sample transcoded results based on a certain sampling rate (i.e. 1 out of 100 segments) and only verifying the random samples. The value of the sampling rate parameter will be influenced by verification computation speed and cost. High computation cost will either require a lower sampling rate or offloading of verification to a third party (in an ideal world, the broadcaster can run verification with a high sampling rate and independently). We have a little more wiggle room for computation speed since the broadcaster can run verification in the background without adding latency to transcoding workflow (i.e. the broadcaster can continue to send segments i + 1, i + 2, etc. while verifying transcoded result i), but the computation speed still should be low enough such that the broadcaster can detect a bad transcoded result in a timely manner because the payments that the broadcaster continues to send with segments while verifying a transcoded result could be value lost by the broadcaster.
- Given that false negatives are inevitable (we can only attempt to push the false negative rate down over time), we are considering mechanisms that avoid heavily penalizing (i.e. taking a large portion of a security deposit) an orchestrator for a false negative. One candidate design has an orchestrator verify all transcoded results before returning them to a broadcaster. If the orchestrator realizes that a transcoded result would fail verification it could transcode the next segment from the broadcaster for free. However, this design is only feasible if the computation speed is low or else the additional latency added to the transcoded stream would be unacceptable

Regardless of the mechanism used, given an input segment and set of transcoded results, we will likely want to verify all the transcoded results for an input segment. So, when we run verification we really mean we run verification on an input segment and its transcoded results. We should determine if there is a meaningful performance difference between running verification N times once for each of the transcoded results for an input segment VS. running verification once for an input segment and its N transcoded results.

When doing the benchmarking it might be helpful to use a configuration that is as close to possible as the likely default configuration used in the Livepeer network. This means:

- Using segment lengths around the default 2 second segment length (allowing for some fluctuation in length around 2 seconds to take into account potential segmenter behavior)
- Use the presets currently supported by the Livepeer network (see: https://github.com/livepeer/lpms/blob/master/ffmpeg/videoprofile.go)

The benchmarking should also be done using each of the supported models (Random Forest, XGBoost, AdaBoost, meta model combining various models, etc.) for each input segment and rendition pair.

Ideally, we end up with a table that includes the computation time and computation cost (perhaps CPU usage, memory usage) along with:

- Input segment length
- Preset
- Model used

When doing benchmarking we can focus on computation time and cost excluding the following operations:

- Video decoding
- Model download

**Comment by ndujar** [comment]
Memory and CPU profiling abilities have been added to the cli.py script. 
Below is the memory_profiling output for an asset (1080p, 30 fps, 3665 kbps) against a watermark attack with the same characteristics:

![image.png](https://images.zenhubusercontent.com/5cf0489817221c71b75cc4e4/5932559c-723c-4062-b8c1-b619f159e1d5)

In the table below it is possible to evaluate the CPU times (in seconds) for the highest level functions in the CLI for different segment sizes:

|  Segment length | Total | Initialization | Renditions Processing | Prediction |
|---|---|---|---|---|
| 1 | 2.878 | 1.323  | 1.460  | 0.002 |
| 2 | 5.484 | 2.663  | 2.697  | 0.026 |
| 4 | 10.665 | 5.067 | 5.503 | 0.004 |

In Initialization we are basically running the same metric extraction functions as in Renditions Processing, only that for the original asset in order to optimize resources (hence yes, there is a meaningful performance difference  whether we run verification once for an input segment and its N transcoded results or not.

Both Renditions Processing and Initialization involve the following breakdown (in percentage):
* Video capture to array: 38.1%
* Metrics computation: 56.6%
* Data aggregation: 5.3%

Deeper detail on a per-function basis can be obtained by means of the tools included in the repo, enabling the do_profiling flag as described in the [README.md](https://github.com/livepeer/verification-classifier/tree/master/cli).
