### ISSUE TITLE
Explore performance enhancements for BRISQUE model using random sampling

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#82]
BRISQUE is not known to be very efficient (there might be some efficient implementations from the OpenCV community?) so there is a chance that the model generated for #81 could be slow.

We might be able to reduce the computation time for the BRISQUE model by randomly sampling frames. Initial exploration seemed to indicate that you can generate BRISQUE data for 240 frames in 24 seconds. So, in theory, if we could randomly sample 10 frames then we can do 10 frames in 1 second. We should explore:

1. If we can use random sampling for BRISQUE data generation without severely negatively impacting the accuracy of the model
2. The computation time of BRISQUE data generation with and without random sampling

2 is of interest because computation time for BRISQUE data generation represents additional overhead for a broadcaster on top of the existing overhead for tamper verification.,

**Comment by ndujar** [comment]
> If we can use random sampling for BRISQUE data generation without severely negatively impacting the accuracy of the model

Experiments have been carried away as part of https://app.zenhub.com/workspaces/transcoding-verification-5ce878fbf542de6fd8ff749b/issues/livepeer/verification-classifier/81
Results show that with only 4 randomly sampled frames, the accuracy for predictions (MAPE) remains at 1.6% (SSIM) and 4.6% (bitrate).
A deeper and more detailed study is in order to extract more informative tables. This should tell us how the prediction error evolves with the number of frames.

> The computation time of BRISQUE data generation with and without random sampling
The computation time at the moment of generation was evaluated at ~10 seconds for ~100 frames in the Google Cloud Platform Cloud Functions (2GB RAM pods).
A thorough study is needed where to extract precise number on a frame basis
