### ISSUE TITLE
Integrate meta model into API

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#89]
At the moment, the API uses the OCSVM tamper model. We have seen better results with a meta model, but it is not integrated into the API yet.

**Comment by ndujar** [comment]
The meta model basically involves the training of a supervised learning algorithm (Catboost Classifier) using the already generated tampered assets as "labeled" input.
To join its discriminating abilities with those of the OC-SVM we use an AND operator that takes positives only when predicted by the OC-SVM and negatives when predicted by the Supervised Learning.
Experimental results so far are shown below:

**UNSUPERVISED TAMPER MODEL ACCURACY**
F20:0.993622081644185 / TNR:0.8980041523033532 / TPR_test:0.9959736456808199

**SUPERVISED TAMPER MODEL ACCURACY**
F20:0.9840017188140828 / TNR:0.9866965547487939 / TPR_test:0.9840243789823622

**TAMPER META-MODEL ACCURACY**
F20: 0.986612181836048 / TNR: 0.9869457066750235 / TPR: 0.9866393352611735

This model can be integrated in the API for further improvement of the current TNR.

**Comment by ndujar** [comment]
- Supervised model was trained and exported to the verification-models/verification.tar.xz file in the GCE bucket
- Code was arranged in API and verifier to adjust and make inference using the new supervised model
- Metamodel code was implemented to output prediction based on prediction from both OC-SVM and SL
- All predictions are included in the API response for debugging
- SL model needs to be checked out as it has too high a False Positive Rate in production.

**Comment by ndujar** [comment]
- Updated the model features in order to simplify the debugging process. Currently all models (SSIM, Supervised Learning and Unsupervised Learning) use the same set of features for simplicity.
- Also, all models use the re-scale to resolution function to have an homogeneous set of inputs in inference.
- Conducted several experiments to assess the behavior in the API. Nevertheless, SL model keeps performing poorly with a False Positive Rate of 1.00 in tests made with YT assets whereas in training it shows a TPR of 0.98 with both YT and Vimeo assets. This affects the accuracy of the metamodel and needs to be corrected.
