### ISSUE TITLE
Test verifier accuracy when renditions transcoded by a GPU

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#98]
We have mainly tested verifier accuracy when renditions are transcoded by a CPU. We would like to test verifier accuracy when renditions are transcoded by a GPU - we don't expect the results to be meaningfully different, but this is a good sanity check.

**Comment by cyberj0g** [comment]
Compared same bitrate FPS-adjusted rendition produced by libx264 codec and by Nvidia H.264 codec from CUDA 10.0. The accuracy is 20% lower for GPU codec renditions. They are generating more False Negatives (with Positive class being 'no tamper').
```
CPU
FPS-adjusted 30-60 FPS renditions report:
              precision    recall  f1-score   support

     Correct       0.81      0.90      0.85        39
      Tamper       0.89      0.79      0.84        39

    accuracy                           0.85        78
   macro avg       0.85      0.85      0.85        78
weighted avg       0.85      0.85      0.85        78
```
```
GPU
FPS-adjusted 30-60 FPS renditions report:
              precision    recall  f1-score   support

     Correct       0.80      0.51      0.62        39
      Tamper       0.64      0.87      0.74        39

    accuracy                           0.69        78
   macro avg       0.72      0.69      0.68        78
weighted avg       0.72      0.69      0.68        78
```

**Comment by cyberj0g** [comment]
Run similar test again after re-training model (see #107). The accuracy for GPU renditions is comparable with CPU renditions. The main reason seem to be the fact bitrate-adjusted renditions were excluded from training data. It's hard for the model to tell apart bitrate tamper rendition and GPU codec generated rendition. The underlying issue is difference in libx264 and Nvenc implementations which don't allow for direct settings mapping when generating renditions. Here are results:
```
CatBoost Full ROC threshold: 0.5
CatBoost Full classification report:
              precision    recall  f1-score   support

           0       0.88      0.71      0.79        62
           1       0.94      0.98      0.96       310

    accuracy                           0.94       372
   macro avg       0.91      0.85      0.87       372
weighted avg       0.93      0.94      0.93       372
```
